stages:
- name: stage1
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: ./build.js
- name: stage2
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tfiduccia/pipline-example:latest
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification:
  recipients:
  - recipient: tani@rancher.com
    notifier: c-l8vnr:n-ww7p5
  - recipient: tanifiduccia@gmail.com
    notifier: c-l8vnr:n-ww7p5
  condition:
  - Success
  - Changed
  - Failed
